# Generated by Django 2.0.2 on 2018-03-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='todo'),
            preserve_default=False,
        ),
    ]
